export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_ERROR = "SET_USER_ERROR";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const GET_SINGLE_BOOK_SUCCESS = "GET_SINGLE_BOOK_SUCCESS";
export const GET_SINGLE_BOOK_REQUEST = "GET_SINGLE_BOOK_REQUEST";
export const GET_SINGLE_BOOK_ERROR = "GET_SINGLE_BOOK_ERROR";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_ERROR = "ADD_BOOK_ERROR";

export const ADD_ASSIGN_BOOK_REQUEST = "ADD_ASSIGN_BOOK_REQUEST";
export const ADD_ASSIGN_BOOK_SUCCESS = "ADD_ASSIGN_BOOK_SUCCESS";
export const ADD_ASSIGN_BOOK_ERROR = "ADD_ASSIGN_BOOK_ERROR";