export const GET_BOOK_LIST_REQUEST = "GET_BOOK_LIST_REQUEST";
export const GET_BOOK_LIST_SUCCESS = "GET_BOOK_LIST_SUCCESS";
export const GET_BOOK_LIST_ERROR = "GET_BOOK_LIST_ERROR";

export const GET_SINGLE_BOOK_SUCCESS = "GET_SINGLE_BOOK_SUCCESS";
export const GET_SINGLE_BOOK_REQUEST = "GET_SINGLE_BOOK_REQUEST";
export const GET_SINGLE_BOOK_ERROR = "GET_SINGLE_BOOK_ERROR";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_ERROR = "ADD_BOOK_ERROR";

export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_ERROR = "UPDATE_BOOK_ERROR";

export const GET_CART_LIST_REQUEST = "GET_CART_LIST_REQUEST";
export const GET_CART_LIST_SUCCESS = "GET_CART_LIST_SUCCESS";
export const GET_CART_LIST_ERROR = "GET_CART_LIST_ERROR";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_ERROR = "CLEAR_CART_ERROR";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
